# .project metadata for Virtual Kubelet
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Set slack_channels
# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "virtual-kubelet"
name: "Virtual Kubelet"
description: "Virtual Kubelet is an open source Kubernetes kubelet implementation"
type: "project"
project_lead: "rbitia" # TODO: AUTO-DETECTED — please verify
# TODO: Set CNCF Slack channel(s)
# slack_channels:
#   - name: "#virtual-kubelet"
#     primary: true

maturity_log:
  - phase: "sandbox"
    date: "2018-12-04T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/1077" # TODO: AUTO-DETECTED — please verify

repositories:
  - "https://github.com/virtual-kubelet/virtual-kubelet"

website: "https://virtual-kubelet.io/"

artwork: "https://landscape.cncf.io/logos/virtual-kubelet.svg"

adopters:
  path: "https://github.com/virtual-kubelet/virtual-kubelet/blob/main/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "virtual-kubelet/virtual-kubelet"

social:
  twitter: "https://twitter.com/virtualkubelet"

security:
  policy:
    path: "https://github.com/virtual-kubelet/virtual-kubelet/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/virtual-kubelet/virtual-kubelet/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/virtual-kubelet/virtual-kubelet/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/cncf/foundation/blob/main/code-of-conduct.md"

legal:
  license:
    path: "https://github.com/virtual-kubelet/virtual-kubelet/blob/main/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/virtual-kubelet/virtual-kubelet/blob/main/README.md"

landscape:
  category: "Runtime"
  subcategory: "Container Runtime"

# CLOMonitor Score: 57/100
# Documentation: 73 | License: 75 | Best Practices: 26 | Security: 59
